FROM docker.io/ubuntu:24.04 AS builder

LABEL maintainer="Brian Vo"

RUN apt-get update && \
    apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    htop \
    iotop \
    iftop \
    atop \
    dstat \
    sysstat \
    nethogs \
    nmon && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y golang && \
    rm -rf /var/lib/apt/lists/*

# Install lazydocker


FROM docker.io/ubuntu:24.04 AS main